### ISSUE TITLE
Create Login command

### ISSUE THREAD

**Issue by Njord201** [mathieurobert1/MyTeams#13]
This command must be login a user.
The command take 1 parameter, the user name.
The function must return these codes according to the context :
- [x] [COMMAND_SUCESS]
- [x] [INVALID_PARAMETER]
- [x] [COMMAND_NOT_SUCESS]

## 📋 Subtasks:
- [x] Check if the command is valid
- [x] Check if the user exist
- [x] Connect the user
